print ("Legends never die when the world is calling you \n can you hear them screaming out your name? \n legends neve die they become a part of you \n every time you bleed reaching greatness \n legends never die")
print ("if you do not give up,you still have a chance, Will Smith")
print ("a string is a stament made by code ")
print ("a int makes it so that a number is only whole and can not be a decimal")
print ("a flot will comvert a equation into a awnser with a decimal ")
print (543/3)
print (int (543/3))
print (543%3)
print (1000%9)
print (int(434/10))
print (3%2)
print (5%5)
print (555/2)
print (123/2)
print (123//2)
print (123%2)
print (764%2)
print (165//2)
print (float (11.13+123))
print (int(100+24.4))